// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (http://www.specflow.org/).
//      SpecFlow Version:2.2.0.0
//      SpecFlow Generator Version:2.2.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace ProteusWeb.FeatureFiles
{
    using TechTalk.SpecFlow;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "2.2.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [NUnit.Framework.TestFixtureAttribute()]
    [NUnit.Framework.DescriptionAttribute("Ability to search for Flights")]
    public partial class AbilityToSearchForFlightsFeature
    {
        
        private TechTalk.SpecFlow.ITestRunner testRunner;
        
#line 1 "AbilityToSearchForFlights.feature"
#line hidden
        
        [NUnit.Framework.OneTimeSetUpAttribute()]
        public virtual void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "Ability to search for Flights", null, ProgrammingLanguage.CSharp, ((string[])(null)));
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [NUnit.Framework.OneTimeTearDownAttribute()]
        public virtual void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        [NUnit.Framework.SetUpAttribute()]
        public virtual void TestInitialize()
        {
        }
        
        [NUnit.Framework.TearDownAttribute()]
        public virtual void ScenarioTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void ScenarioSetup(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioStart(scenarioInfo);
        }
        
        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        public virtual void FeatureBackground()
        {
#line 3
 #line 4
testRunner.Given("I am a Proteus User", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 5
testRunner.And("I have the role: Pro Web Campaigns", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 6
testRunner.And("I go to the Proteus Home URL in my browser", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("01 View Flights - initial load")]
        [NUnit.Framework.CategoryAttribute("SearchOnProWeb")]
        public virtual void _01ViewFlights_InitialLoad()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("01 View Flights - initial load", new string[] {
                        "SearchOnProWeb"});
#line 9
this.ScenarioSetup(scenarioInfo);
#line 3
 this.FeatureBackground();
#line 10
testRunner.When("Login with the correct details (username and password)", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 11
testRunner.Then("The main homepage loads successfully", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 12
testRunner.When("I click on Campaigns from home page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 13
testRunner.Then("The Campaigns page loads successfully", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 14
testRunner.And("All Flights loads which I have access to", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 15
testRunner.And("LogOut ProteusWeb from Campaigns page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("02 Ability to Search fights by Flight Name or Booking Code")]
        [NUnit.Framework.CategoryAttribute("SearchOnProWeb")]
        public virtual void _02AbilityToSearchFightsByFlightNameOrBookingCode()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("02 Ability to Search fights by Flight Name or Booking Code", new string[] {
                        "SearchOnProWeb"});
#line 18
this.ScenarioSetup(scenarioInfo);
#line 3
 this.FeatureBackground();
#line 19
testRunner.When("Login with the correct details (username and password)", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 20
testRunner.Then("The main homepage loads successfully", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 21
testRunner.When("I click on Campaigns from home page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 22
testRunner.Then("All Flights loads which I have access to", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 23
testRunner.And("I can search by Flight Name or Booking Code", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 24
testRunner.And("LogOut ProteusWeb from Campaigns page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("03 Ability to Filter fights by Advertiser or Agency")]
        [NUnit.Framework.CategoryAttribute("SearchOnProWeb")]
        public virtual void _03AbilityToFilterFightsByAdvertiserOrAgency()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("03 Ability to Filter fights by Advertiser or Agency", new string[] {
                        "SearchOnProWeb"});
#line 27
this.ScenarioSetup(scenarioInfo);
#line 3
 this.FeatureBackground();
#line 28
testRunner.When("Login with the correct details (username and password)", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 29
testRunner.Then("The main homepage loads successfully", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 30
testRunner.When("I click on Campaigns from home page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 31
testRunner.Then("All Flights loads which I have access to", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 32
testRunner.And("Filter dropdown fields exist", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 33
testRunner.And("LogOut ProteusWeb from Campaigns page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("04 Ability to use search and filter combinations")]
        [NUnit.Framework.CategoryAttribute("SearchOnProWeb")]
        public virtual void _04AbilityToUseSearchAndFilterCombinations()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("04 Ability to use search and filter combinations", new string[] {
                        "SearchOnProWeb"});
#line 37
this.ScenarioSetup(scenarioInfo);
#line 3
 this.FeatureBackground();
#line 38
testRunner.When("Login with the correct details (username and password)", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 39
testRunner.Then("The main homepage loads successfully", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 40
testRunner.When("I click on Campaigns from home page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 41
testRunner.Then("All Flights loads which I have access to", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 50
  testRunner.And("LogOut ProteusWeb from Campaigns page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("05 Apply button is enabled after entering/selecting search and filters")]
        [NUnit.Framework.CategoryAttribute("SearchOnProWeb")]
        public virtual void _05ApplyButtonIsEnabledAfterEnteringSelectingSearchAndFilters()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("05 Apply button is enabled after entering/selecting search and filters", new string[] {
                        "SearchOnProWeb"});
#line 53
this.ScenarioSetup(scenarioInfo);
#line 3
 this.FeatureBackground();
#line 54
testRunner.When("Login with the correct details (username and password)", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 55
testRunner.Then("The main homepage loads successfully", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 56
testRunner.When("I click on Campaigns from home page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 57
testRunner.Then("All Flights loads which I have access to", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 58
testRunner.When("I search/filter for a particular result", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 59
testRunner.Then("Apply button is enabled", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 60
testRunner.And("LogOut ProteusWeb from Campaigns page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("06 Clear Filters button is enabled after entering/selecting search and filters")]
        [NUnit.Framework.CategoryAttribute("SearchOnProWeb")]
        public virtual void _06ClearFiltersButtonIsEnabledAfterEnteringSelectingSearchAndFilters()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("06 Clear Filters button is enabled after entering/selecting search and filters", new string[] {
                        "SearchOnProWeb"});
#line 63
this.ScenarioSetup(scenarioInfo);
#line 3
 this.FeatureBackground();
#line 64
testRunner.When("Login with the correct details (username and password)", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 65
testRunner.Then("The main homepage loads successfully", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 66
testRunner.When("I click on Campaigns from home page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 67
testRunner.Then("All Flights loads which I have access to", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 68
testRunner.When("I search/filter for a particular result", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 69
testRunner.Then("Clear Filters button is enabled", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 70
testRunner.And("LogOut ProteusWeb from Campaigns page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("07 Flights matching Search/Filter Combination loaded as results")]
        [NUnit.Framework.CategoryAttribute("SearchOnProWeb")]
        public virtual void _07FlightsMatchingSearchFilterCombinationLoadedAsResults()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("07 Flights matching Search/Filter Combination loaded as results", new string[] {
                        "SearchOnProWeb"});
#line 73
this.ScenarioSetup(scenarioInfo);
#line 3
 this.FeatureBackground();
#line 74
testRunner.When("Login with the correct details (username and password)", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 75
testRunner.Then("The main homepage loads successfully", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 76
testRunner.When("I click on Campaigns from home page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 77
testRunner.Then("All Flights loads which I have access to", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 78
testRunner.When("I search/filter for a particular result", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 79
testRunner.And("Click on Apply button", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 80
testRunner.Then("All Flights matching search/filter combination load as results", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 81
testRunner.Then("LogOut ProteusWeb from Campaigns page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("08 Pagination shown when more than 20 flights dispalyed")]
        [NUnit.Framework.CategoryAttribute("SearchOnProWeb")]
        public virtual void _08PaginationShownWhenMoreThan20FlightsDispalyed()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("08 Pagination shown when more than 20 flights dispalyed", new string[] {
                        "SearchOnProWeb"});
#line 85
this.ScenarioSetup(scenarioInfo);
#line 3
 this.FeatureBackground();
#line 86
testRunner.When("Login with the correct details (username and password)", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 87
testRunner.Then("The main homepage loads successfully", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 88
testRunner.When("I click on Campaigns from home page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 89
testRunner.Then("All Flights loads which I have access to", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 90
testRunner.When("I search/filter for a particular result", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 91
testRunner.And("Click on Apply button", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 92
testRunner.Then("All Flights matching search/filter combination load as results", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 94
testRunner.Then("LogOut ProteusWeb from Campaigns page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
    }
}
#pragma warning restore
#endregion
